# Generated by Django 6.0.4 on 2026-07-03 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animalnote'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('category_type', models.CharField(choices=[('operational', 'Operational'), ('capital', 'Capital'), ('maintenance', 'Maintenance'), ('labor', 'Labor'), ('feed', 'Feed'), ('medical', 'Medical'), ('utility', 'Utility'), ('transport', 'Transport'), ('other', 'Other')], default='operational', max_length=20, verbose_name='category type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'expense category',
                'verbose_name_plural': 'expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total amount')),
                ('expense_date', models.DateField(verbose_name='expense date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=20, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment reference')),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='vendor name')),
                ('vendor_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='vendor contact')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='status')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='invoice number')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='receipt')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farms.farm', verbose_name='farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('related_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='animals.animal', verbose_name='related animal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expensive.expensecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['farm', 'expense_date'], name='expensive_e_farm_id_b12c0f_idx'), models.Index(fields=['category'], name='expensive_e_categor_4d9eea_idx'), models.Index(fields=['status'], name='expensive_e_status_632020_idx')],
            },
        ),
    ]
