# Generated by Django 6.0.4 on 2026-06-25 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animalnote'),
        ('farms', '0001_initial'),
        ('productions', '0002_milkproductionsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalProductionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='period type')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total quantity (liters)')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='total sessions')),
                ('average_per_session', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average per session')),
                ('average_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average per day')),
                ('peak_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peak quantity (liters)')),
                ('peak_date', models.DateField(blank=True, null=True, verbose_name='peak date')),
                ('average_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average fat percentage')),
                ('average_snf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average SNF percentage')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_summaries', to='animals.animal', verbose_name='animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_production_summaries', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'animal production summary',
                'verbose_name_plural': 'animal production summaries',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['animal', 'period_start', 'period_end'], name='productions_animal__942458_idx')],
                'unique_together': {('animal', 'period_start', 'period_end')},
            },
        ),
    ]
