# Generated by Django 6.0.4 on 2026-06-25 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('productions', '0003_animalproductionsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('sale_type', models.CharField(choices=[('direct', 'Direct Sale'), ('dairy', 'Dairy/Cooperative'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='direct', max_length=20, verbose_name='sale type')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='buyer name')),
                ('buyer_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='buyer contact')),
                ('buyer_address', models.TextField(blank=True, null=True, verbose_name='buyer address')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity (liters)')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per liter')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total value')),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fat percentage')),
                ('snf_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SNF percentage')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='payment status')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='payment method')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_sales', to='farms.farm', verbose_name='farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_milk_sales', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'milk sale',
                'verbose_name_plural': 'milk sales',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['farm', 'date'], name='productions_farm_id_cdbd9a_idx'), models.Index(fields=['payment_status'], name='productions_payment_a6d8af_idx')],
            },
        ),
    ]
