# Generated by Django 6.0.4 on 2026-07-03 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('productions', '0004_milksale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MilkProductionSummary',
            new_name='DailyProductionSummary',
        ),
        migrations.RenameIndex(
            model_name='dailyproductionsummary',
            new_name='productions_farm_id_071ff3_idx',
            old_name='productions_farm_id_1b2ff1_idx',
        ),
        migrations.RemoveField(
            model_name='milksale',
            name='total_value',
        ),
        migrations.AddField(
            model_name='milksale',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total amount'),
            preserve_default=False,
        ),
    ]
