# Generated by Django 6.0.4 on 2026-06-10 08:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='Tag Number')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('species', models.CharField(choices=[('cow', 'Cow'), ('buffalow', 'Buffalow')], max_length=20, verbose_name='species')),
                ('breed', models.CharField(choices=[('holstein', 'Holstein Friesian'), ('jersey', 'Jersey'), ('gir', 'Gir'), ('sahiwal', 'Sahiwal'), ('red_sindhi', 'Red Sindhi'), ('tharparkar', 'Tharparkar'), ('kankrej', 'Kankrej'), ('ongole', 'Ongole'), ('rathi', 'Rathi'), ('hariana', 'Hariana'), ('crossbred', 'Crossbred'), ('murrah', 'Murrah'), ('surti', 'Surti'), ('jaffarabadi', 'Jaffarabadi'), ('bhadawari', 'Bhadawari'), ('nili_ravi', 'Nili-Ravi'), ('mehsana', 'Mehsana'), ('other', 'Other')], max_length=20, verbose_name='breed')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Birth Weight (kg)')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='color/markings')),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Current Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height (cm)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('pregnant', 'Pregnant'), ('lactating', 'Lactating'), ('dry', 'Dry'), ('heifer', 'Heifer'), ('calf', 'Calf')], default='active', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('lactation_number', models.PositiveIntegerField(default=0, verbose_name='lactation number')),
                ('last_calving_date', models.DateField(blank=True, null=True, verbose_name='last calving date')),
                ('expected_calving_date', models.DateField(blank=True, null=True, verbose_name='expected calving date')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='is pregnant')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='is purchased')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price')),
                ('purchase_farm', models.CharField(blank=True, max_length=255, null=True, verbose_name='purchase farm')),
                ('is_sold', models.BooleanField(default=False, verbose_name='is sold')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='sale date')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='sale price')),
                ('sale_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='sale to')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='animal image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm', verbose_name='farm')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='animals.animal', verbose_name='father')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='animals.animal', verbose_name='mother')),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('checkup', 'Regular Checkup'), ('vaccination', 'Vaccination'), ('deworming', 'Deworming'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('pregnancy_check', 'Pregnancy Check'), ('other', 'Other')], max_length=20, verbose_name='record type')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='symptoms')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='diagnosis')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='treatment')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='medications')),
                ('dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='dosage')),
                ('veterinarian_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='veterinarian name')),
                ('veterinarian_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='veterinarian contact')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='cost')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='follow-up date')),
                ('follow_up_notes', models.TextField(blank=True, null=True, verbose_name='follow-up notes')),
                ('documents', models.FileField(blank=True, null=True, upload_to='health_records/', verbose_name='documents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal', verbose_name='animal')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_health_records', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'animal health record',
                'verbose_name_plural': 'animal health records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalWeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='weight (kg)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_log', to='animals.animal', verbose_name='animal')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_weight_logs', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'animal weight log',
                'verbose_name_plural': 'animal weight logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tag_number'], name='animals_ani_tag_num_962a58_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm'], name='animals_ani_farm_id_46c9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species'], name='animals_ani_species_9bedc5_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['breed'], name='animals_ani_breed_689c85_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status'], name='animals_ani_status_e5c501_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['is_active'], name='animals_ani_is_acti_139d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='animalhealthrecord',
            index=models.Index(fields=['animal'], name='animals_ani_animal__2a4cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='animalhealthrecord',
            index=models.Index(fields=['record_type'], name='animals_ani_record__0cbe4b_idx'),
        ),
        migrations.AddIndex(
            model_name='animalhealthrecord',
            index=models.Index(fields=['date'], name='animals_ani_date_f85c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='animalweightlog',
            index=models.Index(fields=['animal'], name='animals_ani_animal__e0114e_idx'),
        ),
        migrations.AddIndex(
            model_name='animalweightlog',
            index=models.Index(fields=['date'], name='animals_ani_date_e7a345_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='animalweightlog',
            unique_together={('animal', 'date')},
        ),
    ]
