# Generated by Django 6.0.4 on 2026-06-12 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField(default=django.utils.timezone.now, verbose_name='breeding date')),
                ('method', models.CharField(choices=[('natural', 'Natural'), ('ai', 'Artificial Insemination')], default='natural', max_length=20, verbose_name='method')),
                ('semen_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='semen source')),
                ('semen_batch', models.CharField(blank=True, max_length=255, null=True, verbose_name='semen batch number')),
                ('insemination_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='insemination technician')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed Pregnant'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=20, verbose_name='status')),
                ('pregnancy_check_date', models.DateField(blank=True, null=True, verbose_name='pregnancy check date')),
                ('expected_calving_date', models.DateField(blank=True, null=True, verbose_name='expected calving date')),
                ('actual_calving_date', models.DateField(blank=True, null=True, verbose_name='actual calving date')),
                ('calving_notes', models.TextField(blank=True, null=True, verbose_name='calving notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='farms.farm', verbose_name='farm')),
                ('female', models.ForeignKey(limit_choices_to={'gender': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_female', to='animals.animal', verbose_name='female')),
                ('male', models.ForeignKey(blank=True, limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_as_male', to='animals.animal', verbose_name='male')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_breeding', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
        ),
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField(verbose_name='calving date')),
                ('calving_type', models.CharField(choices=[('normal', 'Normal'), ('assisted', 'Assisted'), ('c_section', 'C-Section'), ('difficult', 'Difficult')], default='normal', max_length=20, verbose_name='calving type')),
                ('calf_tag_number', models.CharField(blank=True, max_length=50, verbose_name='calf tag number')),
                ('calf_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='calf gender')),
                ('calf_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='calf weight (kg)')),
                ('calf_health_status', models.CharField(blank=True, max_length=200, verbose_name='calf health status')),
                ('complications', models.TextField(blank=True, verbose_name='complications')),
                ('treatment_given', models.TextField(blank=True, verbose_name='treatment given')),
                ('assisted_by', models.CharField(blank=True, max_length=150, verbose_name='assisted by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('breeding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calving', to='animals.breedingrecord', verbose_name='breeding record')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calving_records', to='farms.farm', verbose_name='farm')),
                ('mother', models.ForeignKey(limit_choices_to={'gender': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='calvings', to='animals.animal', verbose_name='mother')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_calvings', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'calving record',
                'verbose_name_plural': 'calving records',
                'ordering': ['-calving_date'],
            },
        ),
    ]
