# Generated by Django 6.0.4 on 2026-07-13 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'inventory category',
                'verbose_name_plural': 'inventory categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='item code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('item_type', models.CharField(choices=[('feed', 'Animal Feed'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('supply', 'Supply'), ('fodder', 'Fodder'), ('mineral', 'Mineral Supplement'), ('vaccine', 'Vaccine'), ('other', 'Other')], default='other', max_length=20, verbose_name='item type')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('bag', 'Bag'), ('bottle', 'Bottle'), ('unit', 'Unit')], default='kg', max_length=20, verbose_name='unit')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='current quantity')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='reorder level')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum stock')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit cost')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='supplier name')),
                ('supplier_contact', models.CharField(blank=True, max_length=20, verbose_name='supplier contact')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory', verbose_name='category')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('wastage', 'Wastage')], max_length=20, verbose_name='transaction type')),
                ('date', models.DateField(verbose_name='date')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit cost')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total cost')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='supplier name')),
                ('supplier_contact', models.CharField(blank=True, max_length=20, verbose_name='supplier contact')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='invoice number')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance after')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem', verbose_name='item')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'stock transaction',
                'verbose_name_plural': 'stock transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['farm'], name='inventory_i_farm_id_a5b440_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_b07c45_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_type'], name='inventory_i_item_ty_72ee4a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_9e3971_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item', 'date'], name='inventory_s_item_id_288206_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_s_transac_f888de_idx'),
        ),
    ]
