# Generated by Django 6.0.4 on 2026-07-13 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('target_animal', models.CharField(blank=True, max_length=200, verbose_name='target animals')),
                ('preparation_instructions', models.TextField(blank=True, verbose_name='preparation instructions')),
                ('feeding_instructions', models.TextField(blank=True, verbose_name='feeding instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feed_formulas', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_formulas', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'feed formula',
                'verbose_name_plural': 'feed formulas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedFormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.feedformula', verbose_name='formula')),
                ('ingredient', models.ForeignKey(limit_choices_to={'item_type__in': ['feed', 'fodder', 'mineral']}, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_formulas', to='inventory.inventoryitem', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'feed formula ingredient',
                'verbose_name_plural': 'feed formula ingredients',
                'ordering': ['formula', 'ingredient'],
            },
        ),
    ]
